### ISSUE TITLE
Add persistence

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll-studio#12]
The editor should store some information to disk in order to be able to remember where you left off when quitting and restarting. 

The easiest way would probably be storing a SQLite database in a local tmp directory. This database should store information such as
- which project you were working on
- mapping from deploy token to URL
- etc

**Comment by mathisonian** [comment]
@megan-vo I think we can close this?

**Comment by megan-vo** [comment]
@mathisonian yep I think so! Sounds good to me
