### ISSUE TITLE
Better components view

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll-studio#20]
The components view could use some love. It currently looks like this:

<img width="294" alt="Screen Shot 2019-06-07 at 1 14 58 PM" src="https://user-images.githubusercontent.com/1074773/59103325-7834ce80-8926-11e9-903c-c9a619df7074.png">

We should:
1. Add structure so the components are grouped as they are in [the docs](https://idyll-lang.org/docs/components). There should be an additional section for custom components.
2. Add thumbnail images for each components, we can re-use the images from the docs to start. We should also create a default thumbnail for the case where components don't have an associated image.

**Comment by megan-vo** [comment]
Would it be okay to close this issue?

**Comment by mathisonian** [comment]
Yeah!
