### ISSUE TITLE
How do you "Hello World" this?

### ISSUE THREAD

**Issue by zeluspudding** [idyll-lang/idyll-studio#29]
Are there getting started instructions for building / deploying idyll-studio? I've poked through the sub directories and didn't see anything that indicated as much. Also, does publishing via this simply output idyll markeup the we'd then need to host/render somewhere? Or is this more of a full blown content management / publishing system?

**Comment by mathisonian** [comment]
Hey @zeluspudding, we're in the process of cleaning up this repo a bit, once https://github.com/idyll-lang/idyll/pull/511 is merged I'll write up a quick start guide for using & developing the project.

Currently this integrates with [idyll.pub](https://idyll.pub/post/announcing-idyll-pub-0a3eff0661df3446a915700d/) to provide hosting, but you can always grab the compiled output and use your own hosting if preferred.

**Comment by mathisonian** [comment]
I've updated the [developer guide](https://github.com/idyll-lang/idyll-studio/blob/master/CONTRIBUTING.md) to be up to date with all the latest changes, and add a new **[user guide](https://github.com/idyll-lang/idyll-studio/blob/master/USER_GUIDE.md)** that has some more practical details.
