### ISSUE TITLE
Property textbox doesn't update when variable is dragged onto a property

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll-studio#85]
How to reproduce:

Drag-and-drop a variable from the variables panel in the sidebar onto a component's property. The live-updating value of the variable above the textbox maintains the correct value, but the textbox itself should update to reflect the new variable name

**Comment by mathisonian** [comment]
I'm not sure if this is the same error, but similarly: 

if you edit the idyll markup and execute, then switch to the props tab, the changes are missing

**Comment by megan-vo** [comment]
Ah yes, they are definitely related.
