### ISSUE TITLE
Hide dysfunctional and internal elements from sidebar

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll-studio#87]
### Layout

- [ ] fixed
- [ ] inline
- [ ] scroller
- [ ] step
- [ ] steppercontrol

Rename `Text Container` to `Paragraph`

### Logic

- [ ] Case
- [ ] Default

### Presentation

- [ ] Graphic

### Helpers

Hide this category

### Theme / Layout

Hide this section

**Comment by megan-vo** [comment]
Adding onto this:

### Presentation
Header 

### Helpers
Preloader 

Both throw errors when dropped into the document (tag related I suspect)

**Comment by mathisonian** [comment]
The `Header` issues should be fixed by https://github.com/idyll-lang/idyll/pull/696 (in idyll@5.2.4)

**Comment by megan-vo** [comment]
Ah nice! Seems like I have to update my Idyll version 😂
